name: Git Sync
author: Chloe Zhang <xian.zhang@anz.com>
description: Push private repository souce code to public repository
branding:
  icon: 'git-branch'
  color: 'gray-dark'
inputs:
  source_repo:
    description: GitHub repo slug or full clone url
    required: true
  destination_repo:
    description: GitHub repo slug or full clone url
    required: true
  tag:
    description: Tag to sync to
    required: true
  branch:
    description: Branch name to sync to
    required: true
    default: 'master'
  ssh_private_key:
    description: SSH key used to authenticate with git clone urls provided (optional if public or https clone url with authentication)
    required: false
outputs:
  msg:
    description: success or fail message
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
  args:
    - ${{ inputs.source_repo }}
    - ${{ inputs.destination_repo }}
    - ${{ inputs.tag }}
    - ${{ inputs.branch }}
